package com.miaoshaproject.dataobject;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

@TableName("mp_user")
public class MpUserDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_user.id
     *
     * @mbg.generated Thu Mar 30 15:53:27 CST 2023
     */
    @TableId(type = IdType.AUTO) //设置ID 自增长策略
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_user.user_name
     *
     * @mbg.generated Thu Mar 30 15:53:27 CST 2023
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_user.password
     *
     * @mbg.generated Thu Mar 30 15:53:27 CST 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_user.name
     *
     * @mbg.generated Thu Mar 30 15:53:27 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_user.age
     *
     * @mbg.generated Thu Mar 30 15:53:27 CST 2023
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_user.emial
     *
     * @mbg.generated Thu Mar 30 15:53:27 CST 2023
     */
    @TableField(value = "emial")
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_user.id
     *
     * @return the value of mp_user.id
     *
     * @mbg.generated Thu Mar 30 15:53:27 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_user.id
     *
     * @param id the value for mp_user.id
     *
     * @mbg.generated Thu Mar 30 15:53:27 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_user.user_name
     *
     * @return the value of mp_user.user_name
     *
     * @mbg.generated Thu Mar 30 15:53:27 CST 2023
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_user.user_name
     *
     * @param userName the value for mp_user.user_name
     *
     * @mbg.generated Thu Mar 30 15:53:27 CST 2023
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_user.password
     *
     * @return the value of mp_user.password
     *
     * @mbg.generated Thu Mar 30 15:53:27 CST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_user.password
     *
     * @param password the value for mp_user.password
     *
     * @mbg.generated Thu Mar 30 15:53:27 CST 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_user.name
     *
     * @return the value of mp_user.name
     *
     * @mbg.generated Thu Mar 30 15:53:27 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_user.name
     *
     * @param name the value for mp_user.name
     *
     * @mbg.generated Thu Mar 30 15:53:27 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_user.age
     *
     * @return the value of mp_user.age
     *
     * @mbg.generated Thu Mar 30 15:53:27 CST 2023
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_user.age
     *
     * @param age the value for mp_user.age
     *
     * @mbg.generated Thu Mar 30 15:53:27 CST 2023
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_user.emial
     *
     * @return the value of mp_user.emial
     *
     * @mbg.generated Thu Mar 30 15:53:27 CST 2023
     */
    public String getEmial() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_user.emial
     *
     * @param emial the value for mp_user.emial
     *
     * @mbg.generated Thu Mar 30 15:53:27 CST 2023
     */
    public void setEmial(String emial) {
        this.email = emial == null ? null : emial.trim();
    }

    public MpUserDO(String userName, String password, String name, Integer age, String emial) {
        this.userName = userName;
        this.password = password;
        this.name = name;
        this.age = age;
        this.email = emial;
    }

    public MpUserDO() {
    }

    @Override
    public String toString() {
        return "MpUserDO{" +
                "id=" + id +
                ", userName='" + userName + '\'' +
                ", password='" + password + '\'' +
                ", name='" + name + '\'' +
                ", age=" + age +
                ", email='" + email + '\'' +
                '}';
    }
}