#开发环境
spring:
  #mongodb
  data:
    mongodb:
      host: 127.0.0.1
      database: comments
      port: 27017
  #mysql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/miaosha
    name: miaosha
    username: root
    password: 678678
    #druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        #连接池最大连接数（负值表示没有限制）
        max-active: -1
        #最大阻塞时间，单位ms
        max-wait: 2000
        #最大空闲连接数
        max-idle: 100
        #最小空闲连接数
        min-idle: 0
    #连接超时时间，单位ms
    timeout: 2000